### ISSUE TITLE
[Nextjs] ERR_REQUIRE_ESM issue on v8 and above

### ISSUE THREAD

**Issue by nooxx** [near/wallet-selector#860]
**Describe the bug**
After I upgraded @near-wallet-selector/core, @near-wallet-selector/modal-ui, @near-wallet-selector/near-wallet and @near-wallet-selector/wallet-connect to the v8.2.1, I experienced a build error on my nextjs (13) app:

```
- info Compiled successfully
- info Collecting page data .Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/arnosimon/code/kiln/nakamoto/node_modules/@walletconnect/modal/dist/index.js from /Users/arnosimon/code/kiln/nakamoto/node_modules/@near-wallet-selector/wallet-connect/index.cjs not supported.
Instead change the require of index.js in /Users/arnosimon/code/kiln/nakamoto/node_modules/@near-wallet-selector/wallet-connect/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/arnosimon/code/kiln/nakamoto/node_modules/@near-wallet-selector/wallet-connect/index.cjs:9:13)
    at 374 (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1293:18)
    at __webpack_require__ (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:25:42)
    at 1371 (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/chunks/1573.js:24:94)
    at __webpack_require__ (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:25:42)
    at /Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1187:96
    at __webpack_require__.a (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:89:13)
    at 1862 (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1180:21)
    at __webpack_require__ (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:25:42)
    at /Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:33:91
    at __webpack_require__.a (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:89:13)
    at 3287 (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:11:21)
    at __webpack_require__ (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1674:39)
    at /Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1675:116
    at __webpack_require__.X (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/webpack-runtime.js:177:21)
    at /Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1675:47
    at Object.<anonymous> (/Users/arnosimon/code/kiln/nakamoto/services/core/dashboard/.next/server/pages/stake/near.js:1678:3)
    at requirePage (/Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/server/require.js:112:75)
    at /Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/server/load-components.js:80:84
    at async loadComponentsImpl (/Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/server/load-components.js:80:26)
    at async /Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/build/utils.js:1006:32
    at async Span.traceAsyncFn (/Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/trace/trace.js:103:20) {
  code: 'ERR_REQUIRE_ESM'
}

> Build error occurred
Error: Failed to collect page data for /stake/near
    at /Users/arnosimon/code/kiln/nakamoto/node_modules/next/dist/build/utils.js:1156:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

Environment:
node v20.3.0

I tried transpiling the packages as they use CommonJS but without any luck.

**Comment by kujtimprenkuSQA** [comment]
Hi @nooxx, thank you for raising this issue.

The error seems to come from a dependency `@walletconnect/modal` which is used by `@near-wallet-selector/wallet-connect` to show the official QR Modal of WalletConnect.

It looks like when they build this package they do it only in ESM format which in turn has a "type": "module" in the package.json and Next.js seems to not work properly with these kinds of packages.

For all of our packages we publish them in both `ESM` and `CommonJS` format but since the error is coming from `@walletconnect/modal` the only solution we can think of right now is to transpile the `@near-wallet-selector/wallet-connect` in `next.config.js` to `nextConfig` options:


```ts
  transpilePackages: ["@near-wallet-selector/wallet-connect"],
  experimental: {
    esmExternals: "loose"
  }
```

Demo repo: https://github.com/kujtimprenkuSQA/guest-book-nextjs
Live: https://guest-book-nextjs.vercel.app/

**Comment by nooxx** [comment]
Thx! I had my ```esmExternals: true``` but the "loose" fixes it
